In [1]:
!pip install transformers sentence-transformers

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 86.0/86.0 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 1.2/1.2 MB 9.5 MB/s eta 0:00:00
     ------------------------------------- 977.5/977.5 kB 10.3 MB/s eta 0:00:00
     -------------------------------------- 172.3/172.3 MB 7.2 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125960 sha256=2f3103f25889dd8b441695e7c08248cbdf579855f2005443d6ca3a213e76d657
  Stored in directory: c:\users\prashanthkumarreddy\appdata\local\pip\cache\wheels\0a\f5\dd\9d00836c4e9e279c2a59d5b0ab72dafa66cbc626a327c550dd
Successfully built sentence-transformers


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [1]:
import pandas as pd
import os
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import torch
import transformers as ppb
import warnings
warnings.filterwarnings('ignore')

In [2]:
def get_essay_data(verbose=False, words_count=500):
    PATH = "drive/MyDrive/Fall_2023_Project/ghostbuster/"
    PATH = ""
    ESSAY_DATA_PATH = PATH + "essay/data/"
    required_data = ["gpt", "human", "claude"]
    SKIP = ["logprobs"]
    docs, names, labels = [], [], []

    for split in required_data:
        for filename in os.listdir(ESSAY_DATA_PATH + split):
            filepath = os.path.join(ESSAY_DATA_PATH, split, filename)

            if filename in SKIP:
                continue
                
            with open(filepath, encoding="utf8") as f:
                doc = f.read()

            doc = doc.split()[:words_count]
            doc = " ".join(doc)

            filepath = filepath.replace(PATH, "")

            label = 0
            if split == "human":
                label = 1

            if verbose:
                print(filepath)
                
            names.append(filepath)
            docs.append(doc)
            labels.append(label)

    return {
      "names": names,
      "docs": docs,
      "labels": labels
  }


In [3]:
import pandas as pd

res = get_essay_data()

df = pd.DataFrame({
    "txt": res["docs"],
    "filename": res["names"],
    "label": res["labels"]
})
df.shape

(4332, 3)

In [4]:
df.head()

txt                 filename  \
0  Introduction Having children is a crucial aspe...     essay/data/gpt\0.txt   
1  During the Victorian era in England, women wer...     essay/data/gpt\1.txt   
2  Enzymes are essential biological catalysts tha...    essay/data/gpt\10.txt   
3  Memorials represent a crucial part of cultural...   essay/data/gpt\100.txt   
4  English language has three functional categori...  essay/data/gpt\1000.txt   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [5]:
df.label.value_counts()

0    2888
1    1444
Name: label, dtype: int64

In [6]:
# For DistilBERT:
model_class, tokenizer_class, pretrained_weights = (ppb.DistilBertModel, ppb.DistilBertTokenizer, 'distilbert-base-uncased')

## Want BERT instead of distilBERT? Uncomment the following line:
#model_class, tokenizer_class, pretrained_weights = (ppb.BertModel, ppb.BertTokenizer, 'bert-base-uncased')

# Load pretrained model/tokenizer
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_transform.weight', 'vocab_transform.bias', 'vocab_projector.weight', 'vocab_layer_norm.weight', 'vocab_projector.bias', 'vocab_layer_norm.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [7]:
batch_1 = df[:2000]

In [8]:
#df['txt'].apply((lambda x: tokenizer.encode(x, add_special_tokens=True)))

In [9]:
tokenized = batch_1['txt'].apply((lambda x: tokenizer.encode(x, add_special_tokens=True, max_length=512)))

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


In [10]:
tokenized.shape, len(tokenized)

((2000,), 2000)

In [11]:
max_len = max([len(i) for i in tokenized.values])
padded = np.array([i + [0]*(max_len-len(i)) for i in tokenized.values])

In [12]:
np.array(padded).shape

(2000, 512)

In [13]:
padded

array([[  101,  4955,  2383, ..., 10908,  1010,   102],
       [  101,  2076,  1996, ...,  1010,  2005,   102],
       [  101, 16285,  2024, ...,  5377,  1006,   102],
       ...,
       [  101,  4556,  3306, ...,  2019,  3418,   102],
       [  101,  1996,  6614, ...,  1012,  1996,   102],
       [  101,  1996,  2364, ...,  1012,  2036,   102]])

In [14]:
attention_mask = np.where(padded != 0, 1, 0)
attention_mask.shape

(2000, 512)

In [15]:
attention_mask[:5]

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [16]:
input_ids = torch.tensor(padded)
attention_masks = torch.tensor(attention_mask)

with torch.no_grad():
    last_hidden_states = model(input_ids, attention_mask=attention_masks)

In [17]:
features = last_hidden_states[0][:,0,:].numpy()

In [18]:
features

array([[-0.21086547, -0.00548651, -0.44475728, ..., -0.40019983,
         0.18505082,  0.46580416],
       [-0.3340324 ,  0.12804615, -0.66982174, ..., -0.20458105,
         0.19250229,  0.60319567],
       [-0.4694301 , -0.14065003, -0.20904969, ..., -0.23931995,
         0.26219547,  0.5047539 ],
       ...,
       [-0.19655776,  0.21621853, -0.46567416, ..., -0.40297642,
         0.5279088 ,  0.42661187],
       [-0.22044837, -0.28241214,  0.13684055, ..., -0.14661334,
         0.55254537,  0.34577167],
       [-0.33575684, -0.22789533,  0.06581112, ...,  0.06670486,
         0.34214625,  0.3974522 ]], dtype=float32)